language: objective-c

osx_image: xcode11.6

xcode_project: FloatingBottomSheetView.xcodeproj

xcode_scheme: FloatingBottomSheetViewTests

xcode_destination: platform=iOS Simulator, OS=13.6, name=iPhone 7