language: objective-c

osx_image: xcode11.6
env:
  matrix:
    - TEST_SDK=iphonesimulator13.6 OS=13.6 NAME='iPhone 11'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage NO -project FloatingBottomSheetView.xcodeproj -scheme FloatingBottomSheetView -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES